repos:
  - repo: local
    hooks:
      - id: run-biome
        name: "Run Biome"
        entry: pnpx @biomejs/biome check --write --no-errors-on-unmatched --files-ignore-unknown=true
        language: system
        types: [text]
        stages: [ "pre-commit" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
