name: 'OctoSTS'
description: |
  This action exchanges the workflow's identity token for a GitHub App Token from the OctoSTS service,
  in accordance withe the configured trust policy at the repo, or organisation, level.

inputs:
  domain:
    description: The domain of the OctoSTS instance to federate against.
    default: octo-sts.dev

  scope:
    description: The org, and optionally repo, of the repository which contains the trust policy.
    required: true

  identity:
    description: |
      The name of the trust policy to load from the target repository provided in the scope input. The trust policy
      is loaded from the provided scope repository, and the filepath .github/chainguard/{identity}.sts.yaml
    required: true

outputs:
  token:
    description: The federated token to use for authentication
    value: ${{ steps.octo-sts.outputs.token }}

runs:
  using: node20
  main: 'dist/run/index.js'
  post: 'dist/post-run/index.js'
