name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm biome ci
      - run: pnpm run format
      - name: Verify that generated code is committed
        run: |
          results=$(git status --porcelain)
          if [[ -n "$results" ]]; then
            echo "Tree has changes:"
            echo "$results"
            echo "---------------------------------"
            git --no-pager diff
            exit 1
          fi
        shell: bash

  compile:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run release
      - name: Verify that generated code is committed
        run: |
          results=$(git status --porcelain)
          if [[ -n "$results" ]]; then
            echo "Tree has changes:"
            echo "$results"
            echo "---------------------------------"
            git --no-pager diff
            exit 1
          fi
        shell: bash
