name: Publish Major Version
on:
  workflow_dispatch:
    inputs:
      major-version:
        description: 'Major version to publish'
        required: true
        options:
          - v1
      commit-sha:
        description: 'Commit SHA to use for this version'
        required: true

jobs:
  publish-major-version:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.commit-sha }}
      - run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
      - run: git tag -a "${{ github.event.inputs.major-version }}" ${{ github.event.inputs.commit-sha }}
      - run: git push origin "${{ github.event.inputs.major-version }}"
